name: Bot Actions
run-name: Bot Pipeline go! ğŸš€
on:
  push:
    branches: ["master", "hw9"]
#    paths:
#      - 'app/bot/**'
  pull_request:
    branches: ["master", "hw9"]
    paths:
      - 'app/bot/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn package -pl bot -am -DskipTests
        working-directory: app
      - name: Build Docker image
        run: docker build -t bot-image -f app/bot/Dockerfile .

