name: Scrapper Actions
run-name: Scrapper Pipeline go! ğŸš€
on:
  push:
    branches: ["master", "hw9"]
  pull_request:
    branches: ["master", "hw9"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/app
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: List files in the repository v2
        run: |
          ls ${{ github.workspace }}  
      - name: Build with Maven
        run: mvn package -pl app.scrapper -am 