name: Scrapper Actions
run-name: Scrapper Pipeline go! ğŸš€
on:
  push:
    branches: ["master", "hw9"]
#    paths:
#      - 'app/scrapper/**'
  pull_request:
    branches: ["master", "hw9"]
    paths:
      - 'app/scrapper/**'

env:
  REGISTRY: ghcr.io

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."

      - name: List files in the repository
        run: |
          ls -la ${{ github.workspace }}

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn package -pl scrapper -am -DskipTests
        working-directory: app

      - name: Build Docker image
#        run: docker build -t ${{ env.REGISTRY }}/scrapper-image -f app/scrapper/Dockerfile .
        run: docker build -t ${{ env.REGISTRY }}/${{ github.actor }}/scrapper-image -f app/scrapper/Dockerfile .

      - run: echo "${{ secrets.GITHUB_TOKEN }}"

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GH Packages
#        run: docker push ${{ env.REGISTRY }}/scrapper-image
        run: docker push ${{ env.REGISTRY }}/${{ github.actor }}/scrapper-image

